# NUMPY

In [2]:
list1=[4,2,3,1]
list2=[3,6,9,2]


In [3]:
sum_1=list1+list2

In [4]:
sum_1

[4, 2, 3, 1, 3, 6, 9, 2]

In [6]:
for num1, num2 in zip(list1,list2):
    print(num1+num2)


7
8
12
3


In [ ]:
sum_1=[]


In [11]:
sum_1=[]
for num1, num2 in zip(list1,list2):
    sum_1.append(num1+num2)
print(sum_1)


[7, 8, 12, 3]


In [ ]:
# NUMPY


In [12]:
import numpy as np


In [15]:
arr1=np.array(list1)

In [16]:
arr1

array([4, 2, 3, 1])

In [17]:
arr2=np.array(list2)

In [18]:
type(arr1)

numpy.ndarray

In [19]:
arr1.ndim

1

In [26]:
list3=[[1,2,4],[6,9,8]]

In [27]:
arr3=np.array(list3)

In [28]:
arr3

array([[1, 2, 4],
       [6, 9, 8]])

In [29]:
type(arr3)

numpy.ndarray

In [30]:
arr3.ndim

2

In [31]:
arr3.dtype

dtype('int32')

In [32]:
arr3.shape

(2, 3)

In [35]:
arr4=np.array(list3,dtype=float)
arr4

array([[1., 2., 4.],
       [6., 9., 8.]])

In [36]:
arr4.dtype

dtype('float64')

In [37]:
arr5=np.array(['5','10','15','20'])

In [38]:
arr5

array(['5', '10', '15', '20'], dtype='<U2')

In [39]:
arr6=np.array(arr5,dtype=int)

In [40]:
arr6

array([ 5, 10, 15, 20])

In [42]:
arr6.dtype

dtype('int32')

In [43]:
list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [44]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [46]:
np.arange(2,8)

array([2, 3, 4, 5, 6, 7])

In [47]:
arr7=np.arange(2,10)

In [48]:
arr7

array([2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr7.reshape(4,2)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
arr7.reshape(2,4)

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [66]:
arr8=np.arange(2,15)

In [67]:
arr8

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [68]:
arr8[7]

9

In [69]:
arr8[4:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [70]:
arr8[:6]

array([2, 3, 4, 5, 6, 7])

In [73]:
arr8[[1,5,12]]

array([ 3,  7, 14])

In [75]:
arr9=np.array([[2,-3,6,8],[-3,8,9,-7],[5,8,-4,-7],[7,9,-1,9]])

In [76]:
arr9

array([[ 2, -3,  6,  8],
       [-3,  8,  9, -7],
       [ 5,  8, -4, -7],
       [ 7,  9, -1,  9]])

In [77]:
arr9[2]

array([ 5,  8, -4, -7])

In [78]:
arr9[2,3]

-7

In [81]:
arr9[0:2]

array([[ 2, -3,  6,  8],
       [-3,  8,  9, -7]])

In [82]:
arr9[1:]

array([[-3,  8,  9, -7],
       [ 5,  8, -4, -7],
       [ 7,  9, -1,  9]])

In [83]:
arr9[::]

array([[ 2, -3,  6,  8],
       [-3,  8,  9, -7],
       [ 5,  8, -4, -7],
       [ 7,  9, -1,  9]])

In [84]:
arr9[:,1]

array([-3,  8,  8,  9])

In [85]:
arr9[1,:]

array([-3,  8,  9, -7])

In [87]:
arr9[1:3,1:3]

array([[ 8,  9],
       [ 8, -4]])

In [88]:
arr10=np.arange(10,82,2)

In [107]:
arr10

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [114]:
arr10=arr10.reshape(6,6)

In [115]:
arr10[:,[1,4]]

array([[12, 18],
       [24, 30],
       [36, 42],
       [48, 54],
       [60, 66],
       [72, 78]])

In [116]:
arr11=arr10[:,1:4]

In [117]:
arr11

array([[12, 14, 16],
       [24, 26, 28],
       [36, 38, 40],
       [48, 50, 52],
       [60, 62, 64],
       [72, 74, 76]])

In [118]:
arr11.shape

(6, 3)

In [119]:
arr11.shape[0]

6

In [120]:
arr11.shape[1]

3

In [121]:
arr11.size

18

In [122]:
arr12=np.array([25,50,75,100])

In [124]:
arr12.sum()

250

In [125]:
np.sum(arr12)

250

In [127]:
arr12.mean()

62.5

In [128]:
np.mean(arr12)

62.5

In [131]:
np.median(arr12)

62.5

In [132]:
arr11.sum()

792

In [133]:
arr11.sum(axis=0)

array([252, 264, 276])

In [134]:
arr11.sum(axis=1)

array([ 42,  78, 114, 150, 186, 222])

In [137]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [140]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [141]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [143]:
np.random.rand(2,3)

array([[0.84438575, 0.35426067, 0.13459934],
       [0.11267523, 0.92819228, 0.35060544]])

# PANDAS

In [144]:
import pandas as pd

In [147]:
marks=pd.Series([23,54,66,29])


In [148]:
marks

0    23
1    54
2    66
3    29
dtype: int64

In [149]:
score = pd.Series([45,76,55,77],index=['alfred','airene','malavika','sreelakshmi'])

In [150]:
score

alfred         45
airene         76
malavika       55
sreelakshmi    77
dtype: int64

In [154]:
score['airene']

76

In [156]:
score[1]

76

In [159]:
score[['alfred','sreelakshmi']]

alfred         45
sreelakshmi    77
dtype: int64

In [160]:
score>50

alfred         False
airene          True
malavika        True
sreelakshmi     True
dtype: bool

In [161]:
score[score>50]

airene         76
malavika       55
sreelakshmi    77
dtype: int64

In [162]:
score.min()

45

In [165]:
score[(score>50)&(score<60)]

malavika    55
dtype: int64

In [166]:
score+2

alfred         47
airene         78
malavika       57
sreelakshmi    79
dtype: int64

In [167]:
score.sort_values()

alfred         45
malavika       55
airene         76
sreelakshmi    77
dtype: int64

In [177]:
score.sort_values(ascending= False)

sreelakshmi    77
airene         76
malavika       55
alfred         45
dtype: int64

In [178]:
#CREATING A SERIES OBJECT WITH DICTIONARY

In [183]:
temp={"kearala":25,"tn":30,"jk":10,"karanataka":30}

In [184]:
temp=pd.Series(temp)

In [185]:
temp

kearala       25
tn            30
jk            10
karanataka    30
dtype: int64

In [188]:
states=["kearala","JK","AP","JK"]
temp2=pd.Series(temp,index=states)

In [189]:
temp2

kearala    25.0
JK          NaN
AP          NaN
JK          NaN
dtype: float64

In [190]:
temp2[temp2.isna()]

JK   NaN
AP   NaN
JK   NaN
dtype: float64

In [191]:
temp2.notna()

kearala     True
JK         False
AP         False
JK         False
dtype: bool

# PANDAS DATARAME

In [192]:
score={"nida":[45,34,34,44],"adhithyan":[56,44,88,33],"aswin":[55,88,45,77],"sanjay":[67,58,87,55]}

In [193]:
df=pd.DataFrame(score)

In [194]:
df

nida  adhithyan  aswin  sanjay
0    45         56     55      67
1    34         44     88      58
2    34         88     45      87
3    44         33     77      55

In [195]:
sub=['ENG','C','PYTHON','MATHS']

In [200]:
df1=pd.DataFrame(score,index=sub)

In [201]:
df1

nida  adhithyan  aswin  sanjay
ENG       45         56     55      67
C         34         44     88      58
PYTHON    34         88     45      87
MATHS     44         33     77      55

In [206]:
df2=pd.DataFrame(df1,columns=["nida","justin","aswin","sanjay"])

In [207]:
df2

nida  justin  aswin  sanjay
ENG       45     NaN     55      67
C         34     NaN     88      58
PYTHON    34     NaN     45      87
MATHS     44     NaN     77      55

In [210]:
df2["justin"]=[99,66,88,33]

In [211]:
df2

nida  justin  aswin  sanjay
ENG       45      99     55      67
C         34      66     88      58
PYTHON    34      88     45      87
MATHS     44      33     77      55

In [214]:
df2['Average']=(df2['nida']+df2["justin"]+df2["aswin"]+df2["sanjay"])/4

In [215]:
df2

nida  justin  aswin  sanjay  Average
ENG       45      99     55      67    66.50
C         34      66     88      58    61.50
PYTHON    34      88     45      87    63.50
MATHS     44      33     77      55    52.25

In [218]:
df2.drop('C')

nida  justin  aswin  sanjay  Average
ENG       45      99     55      67    66.50
PYTHON    34      88     45      87    63.50
MATHS     44      33     77      55    52.25

In [219]:
df2.drop("Average",axis=1,inplace=True)

In [222]:
df3=df2.drop("nida",axis=1)

In [223]:
df3

justin  aswin  sanjay
ENG         99     55      67
C           66     88      58
PYTHON      88     45      87
MATHS       33     77      55

In [224]:
df3.drop("aswin",axis=1,inplace=True)

In [225]:
df3

justin  sanjay
ENG         99      67
C           66      58
PYTHON      88      87
MATHS       33      55